version: '3.8'

services:
  db:
    image: postgres:15
    container_name: vacantes_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-vacantes_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cambiame}
      POSTGRES_DB: ${POSTGRES_DB:-vacantes_colombia}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
