"""Initial migration

Revision ID: 50e6eae12408
Revises: 
Create Date: 2026-03-11 21:08:08.919327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50e6eae12408'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('pagina_actual', sa.Integer(), nullable=True),
    sa.Column('total_registros', sa.Integer(), nullable=True),
    sa.Column('registros_nuevos', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_sessions_id'), 'scrape_sessions', ['id'], unique=False)
    op.create_table('vacantes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_vacante', sa.String(length=50), nullable=False),
    sa.Column('titulo_vacante', sa.String(length=500), nullable=True),
    sa.Column('descripcion_vacante', sa.Text(), nullable=True),
    sa.Column('cargo', sa.String(length=300), nullable=True),
    sa.Column('nivel_estudios', sa.String(length=100), nullable=True),
    sa.Column('rango_salarial', sa.String(length=100), nullable=True),
    sa.Column('tipo_contrato', sa.String(length=100), nullable=True),
    sa.Column('cantidad_vacantes', sa.SmallInteger(), nullable=True),
    sa.Column('meses_experiencia_cargo', sa.Integer(), nullable=True),
    sa.Column('sector_economico', sa.String(length=200), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('municipio', sa.String(length=150), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_vencimiento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('teletrabajo', sa.Boolean(), nullable=True),
    sa.Column('discapacidad', sa.Boolean(), nullable=True),
    sa.Column('hidrocarburos', sa.Boolean(), nullable=True),
    sa.Column('plaza_practica', sa.Boolean(), nullable=True),
    sa.Column('detalles_prestador', sa.JSON(), nullable=True),
    sa.Column('fecha_scraping', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacantes_codigo_vacante'), 'vacantes', ['codigo_vacante'], unique=True)
    op.create_index(op.f('ix_vacantes_departamento'), 'vacantes', ['departamento'], unique=False)
    op.create_index(op.f('ix_vacantes_fecha_publicacion'), 'vacantes', ['fecha_publicacion'], unique=False)
    op.create_index(op.f('ix_vacantes_sector_economico'), 'vacantes', ['sector_economico'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacantes_sector_economico'), table_name='vacantes')
    op.drop_index(op.f('ix_vacantes_fecha_publicacion'), table_name='vacantes')
    op.drop_index(op.f('ix_vacantes_departamento'), table_name='vacantes')
    op.drop_index(op.f('ix_vacantes_codigo_vacante'), table_name='vacantes')
    op.drop_table('vacantes')
    op.drop_index(op.f('ix_scrape_sessions_id'), table_name='scrape_sessions')
    op.drop_table('scrape_sessions')
    # ### end Alembic commands ###
